import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { ClientProviders } from './provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'What If',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html>
            <body>
                <ClientProviders>{children}</ClientProviders>
            </body>
        </html>
    );
}
